### ISSUE TITLE
Build type is always set to DEBUG when generator is MSVC

### ISSUE THREAD

**Issue by nikitalita** [Starfield-Reverse-Engineering/CommonLibSF#201]
`CMAKE_BUILD_TYPE` does nothing for MSVC generators

see here: https://discourse.cmake.org/t/cmake-build-disregards-cmake-build-type-for-the-visual-studio-generator/4051

**Comment by ThirdEyeSqueegee** [comment]
Apparently CMAKE_CONFIGURATION_TYPES needs to be used for multi-config generators instead of CMAKE_BUILD_TYPE
