### ISSUE TITLE
Conventional Commits

### ISSUE THREAD

**Issue by alandtse** [Starfield-Reverse-Engineering/CommonLibSF#5]
Given that the few commits we have are following this, any issue with adopting [it](https://www.conventionalcommits.org/en/v1.0.0/)?

Benefits is we can auto generate changelogs with various tools if we follow it.

**Comment by ThirdEyeSqueegee** [comment]
Added to [Contributing](https://github.com/Starfield-Reverse-Engineering/CommonLibSF/wiki/Contributing) wiki page
