### ISSUE TITLE
Plugin compilation fails for clang-cl

### ISSUE THREAD

**Issue by ThirdEyeSqueegee** [Starfield-Reverse-Engineering/CommonLibSF#58]
Building the CLibSFPluginTemplate with a clang-cl preset causes the compiler to emit the following errors:
```
SFSE\API.cpp.obj: is not a native COFF file. Recompile without /GL?
SFSE\Interfaces.cpp.obj: is not a native COFF file. Recompile without /GL?
```
It would seem that the MSVC-compiled version of the library is in use here while a clang-cl-compiled version is desired. I'm not sure how to fix this so any insight is appreciated. Naively, I'd like to be able to decide which build config for CommonLibSF to use from within a plugin project--in this case, I'd like to be able to build CommonLibSF (consumed as a vcpkg package) with a clang-cl preset so that I can (presumably) go on to successfully build my plugin with clang-cl and not run into weird file format errors. Is this something that can be worked around?

**Comment by gottyduke** [comment]
I just tested on my plugin template and it can compile with LLVM-clang-cl with both submodule and vcpkg port(I manually added `vcpkg-configuration.json` and modifed CMakeLists.txt). This is likely a problem with your template instead of CLib.

**Comment by ThirdEyeSqueegee** [comment]
Idk, I tried it with all kinds of different flags passed to clang-cl and lld-link (including the defaults) but got the same result every time, same two files. The reason I'm inclined to think it's a library-side issue is that the errors reference CLibSF files. Gonna leave this open in case anyone's encountered this before/knows a fix
