### ISSUE TITLE
Building Multi-threaded (/MT) instead of Multi-threaded DLL (/MD)

### ISSUE THREAD

**Issue by TommInfinite** [Starfield-Reverse-Engineering/CommonLibSF#71]
Hi!
Is there a way for me to build CLibSFPluginTemplate(https://github.com/Starfield-Reverse-Engineering/CLibSFPluginTemplate) with CommonLibSF.lib and other requirements(xbyak fmt,etc) in Multi-threaded (/MT) mode  instead of Multi-threaded DLL (/MD)?

When I try to link another Multi-threaded (/MT) library(which I cannot build by myself) compiler gives me an error because both /MD and /MT libs are present in the project.

**Comment by gottyduke** [comment]
This is a problem from that specific template, not CommonLibSF itself. When I adjusted my template triplet to `x64-windows-static` and runtime to `/MT`, project still builds correctly.

**Comment by ThirdEyeSqueegee** [comment]
It's not a "problem with the template", it's just something that needs to be manually adjusted bc the default triplet is `x64-windows-static-md` with dynamic runtime linking

**Comment by TommInfinite** [comment]
Thanks, the solution worked.
Also I sent a PR to configure that in python script.
