### ISSUE TITLE
`add_commonlibsf_plugin` CMake command

### ISSUE THREAD

**Issue by ThirdEyeSqueegee** [Starfield-Reverse-Engineering/CommonLibSF#8]
CommonLibSSE-NG offers an `add_commonlibsse_plugin` command that takes care of some of the housekeeping for plugin projects--we should add such a command here as well

**Comment by gottyduke** [comment]
This is dependent on the acutal vcpkg registry setup and how to serve the plugin templates

**Comment by ThirdEyeSqueegee** [comment]
Let's look into this after #13 is closed
